config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
]

main/urls.py
from django.urls import path

from main.apps import MainConfig
from main.views import ItemDetailView, BuyCreate, OrderBuyCreate, \
    GetSuccessResponse, GetCancelResponse

app_name = MainConfig.name

urlpatterns = [
    path('item/<int:pk>/', ItemDetailView.as_view(), name='item'),
    path('buy/<int:pk>/', BuyCreate.as_view(), name='buy'),
    path('buy_order/<int:pk>/', OrderBuyCreate.as_view(), name='buy-order'),
    path('success/', GetSuccessResponse.as_view(), name='success'),
    path('cancel/', GetCancelResponse.as_view(), name='cancel'),
]

main/models.py
from django.db import models
from django.db.models import TextChoices

from main.utils import get_exchange_rate


class CurrencyChoice(TextChoices):
    rub = "rub"
    usd = "usd"


class Item(models.Model):
    name = models.CharField(max_length=255, verbose_name='название')
    description = models.TextField(verbose_name='описание', null=True, blank=True)
    price = models.FloatField(verbose_name='цена')
    currency = models.CharField(max_length=3, choices=CurrencyChoice)

    def __str__(self):
        return f'{self.name}, цена {self.price}'

    class Meta:
        verbose_name = 'товар'
        verbose_name_plural = 'товары'


class Discount(models.Model):
    """Модель Discount, которую можно прикрепить к модели Order"""
    value = models.FloatField(verbose_name='размер скидки')

    def __str__(self):
        return f'{self.value}'

    class Meta:
        verbose_name = 'скидка'
        verbose_name_plural = 'скидки'


class Tax(models.Model):
    """Модель Tax, которую можно прикрепить к модели Order"""
    value = models.FloatField(verbose_name='размер налога')

    def __str__(self):
        return f'{self.value}'

    class Meta:
        verbose_name = 'налог'
        verbose_name_plural = 'налоги'


class ItemOrder(models.Model):
    """Модель ItemOrder, которая связывает Item и Order"""
    item = models.ForeignKey(Item, verbose_name="товар", on_delete=models.CASCADE)
    order = models.ForeignKey("Order", verbose_name="заказ", on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(verbose_name="количество")

    def __str__(self):
        return f"{self.order}: {self.item}, {self.quantity}"

    @property
    def full_price(self):
        """Высчитывает полную стоимость продукта в заказе"""
        if self.item.currency == "usd":
            rate = get_exchange_rate(self.item.currency)
            price = round(self.item.price / rate, 2)

        else:
            price = self.item.price

        return round(price * self.quantity, 2)

    class Meta:
        verbose_name = 'товар в заказе'
        verbose_name_plural = 'товары в заказах'


class Order(models.Model):
    """Модель Order, в которой можно объединить несколько Items"""
    items = models.ManyToManyField(
        Item, through='ItemOrder', through_fields=('order', 'item')
    )

    tax = models.ForeignKey(Tax, verbose_name="налог", null=True, blank=True, on_delete=models.SET_NULL)
    discount = models.ForeignKey(Discount, verbose_name="скидка", null=True, blank=True, on_delete=models.SET_NULL)

    def __str__(self):
        return f"{self.pk}"

    @property
    def order_full_price(self):
        """Высчитывает полную стоимость заказа"""
        items = self.items.through.objects.filter(order=self)
        prices = [
            round(item.full_price, 2) for item in items
        ]
        return round(sum(prices), 2)

    class Meta:
        verbose_name = 'заказ'
        verbose_name_plural = 'заказы'

main/views.py
from django.conf import settings
from rest_framework import status
from rest_framework.generics import RetrieveAPIView, get_object_or_404
from rest_framework.renderers import TemplateHTMLRenderer
from rest_framework.response import Response
from rest_framework.views import APIView

from main.models import Item, Order
from main.services import create_stripe_session, create_stripe_tax, create_stripe_discount


class ItemDetailView(RetrieveAPIView):
    queryset = Item.objects.all()
    renderer_classes = [TemplateHTMLRenderer]

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()

        return Response({'item': self.object, 'public_key': settings.STRIPE_PUBLIC_KEY},
                        template_name='main/item_detail.html')


class BuyCreate(APIView):

    def get(self, request, pk, format=None):
        item = get_object_or_404(Item, pk=pk)

        path = f"{self.request.scheme}://{self.request.META.get('HTTP_HOST')}/"

        session = create_stripe_session(price=int(item.price), name=item.name, currency=item.currency, path=path)
        return Response(data={'session_id': session}, status=status.HTTP_200_OK)


class OrderBuyCreate(APIView):

    def get(self, request, pk, format=None):
        order = get_object_or_404(Order, pk=pk)

        path = f"{self.request.scheme}://{self.request.META.get('HTTP_HOST')}/"
        tax, discount = None, None

        if order.tax:
            tax = create_stripe_tax(order.tax.value)

        if order.discount:
            discount = create_stripe_discount(order.discount.value)

        session = create_stripe_session(
            price=int(order.order_full_price), name=order.pk, tax=tax, discount=discount, path=path
        )
        return Response(data={'session_id': session}, status=status.HTTP_200_OK)


class GetSuccessResponse(APIView):
    renderer_classes = [TemplateHTMLRenderer]

    def get(self, request, *args, **kwargs):
        return Response(template_name='main/success.html')


class GetCancelResponse(APIView):
    renderer_classes = [TemplateHTMLRenderer]

    def get(self, request, *args, **kwargs):
        return Response(template_name='main/cancel.html')

main/templates/main/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title> {{ object.name }}</title>
    <script src="https://js.stripe.com/v3/"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  </head>
  <body>
    {% block content %}
    {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  </body>
</html>

main/templates/main/cancel.html
{% extends 'main/base.html' %}

{% block content %}
<div class="container text-center">
  <div class="row justify-content-md-center">
    <div class="card align-self-center text-bg-danger" style="width: 40rem;">
      <div class="card-body">
          <h5 class="card-title">Оплата не прошла</h5>
      </div>
    </div>
  </div>
</div>
{% endblock %}

main/templates/main/item_detail.html
{% extends 'main/base.html' %}

{% block content %}
<div class="container text-center">
  <div class="row justify-content-md-center">
    <div class="card align-self-center" style="width: 40rem;">
      <div class="card-body">
        <h4 class="card-title"> {{ item.name }}</h4>
        <h6> {{ item.price }} </h6>
        {% if item.text %}
            <p class="card-text">{{ item.text }}</p>
        {% endif %}
        <button class="btn btn-primary" type="button" id="checkout-button">Buy</button>
        <script>
          const stripe = Stripe('{{ public_key }}');
          const checkoutButton = document.getElementById('checkout-button');
          checkoutButton.addEventListener('click', function() {
            fetch("{% url 'main:buy' item.pk %}", {
                          method: "GET",
                          })
            .then(function(response) {
                return response.json();
                })
            .then(function(session) {
                return stripe.redirectToCheckout({ sessionId: session.session_id });
                })
            .then(function(result) {
                if (result.error) {
                    alert(result.error.message);
                }
                });
            });
        </script>

      </div>
    </div>
  </div>
</div>
{% endblock %}

main/templates/main/success.html
{% extends 'main/base.html' %}

{% block content %}
<div class="container text-center">
  <div class="row justify-content-md-center">
    <div class="card align-self-center text-bg-success" style="width: 40rem;">
      <div class="card-body">
          <h5 class="card-title">Оплата прошла успешно</h5>
      </div>
    </div>
  </div>
</div>
{% endblock %}